name: Renderizar Equações LaTeX

on:
  push:
    branches:
      - main  # Aciona em pushes na branch 'main'
    paths:
      - '**/*.md'  # Apenas quando arquivos .md forem modificados

jobs:
  render_latex:
    runs-on: ubuntu-latest  # Usa ambiente Linux

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Python no ambiente
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 3: Instalar dependências necessárias
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib markdown

      # Passo 4: Rodar o script de renderização
      - name: Renderizar equações LaTeX
        run: |
          python render_latex_markdown.py  # Executa o script de renderização

      # Passo 5: Configurar usuário do Git para commits automáticos
      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Passo 6: Commitar e enviar alterações
      - name: Commit e Push alterações
        run: |
          git add .  # Adiciona as alterações
          git commit -m "Renderizar equações LaTeX como imagens"  # Faz commit
          git push  # Envia para o repositório
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
